name: 5 - Trigger Manual (workflow_dispatch)

on:
  workflow_dispatch:
    inputs:
      nivel_alerta:
        description: 'Selecciona el nivel de alerta'
        required: true
        default: 'bajo'
        type: choice
        options:
          - bajo
          - medio
          - alto
          - critico

jobs:
  mensaje-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir nivel de alerta
        run: echo "Nivel de alerta seleccionado: ${{ github.event.inputs.nivel_alerta }}"
